#!/usr/bin/env python3
"""
Publish one finished episode into this feed repo.

Takes a script .md file from the private Personal-Podcast source repo (which must
have a matching .mp3 alongside it, already generated by tts/generate.py), copies
the audio here, extracts metadata, updates episodes.json, regenerates feed.xml,
and commits + pushes this repo.

Run with the TTS venv's Python (needs imageio_ffmpeg for duration extraction):
    C:\\AI\\ppod-tts\\venv\\Scripts\\python.exe publish_episode.py <path\\to\\episode.md>

Called as the final step of the source repo's /episode and /deep-dive skills.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MANIFEST = HERE / "episodes.json"
EPISODES_DIR = HERE / "episodes"


def parse_frontmatter(md: str) -> dict:
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", md, re.DOTALL)
    if not m:
        raise SystemExit("ERROR: no YAML frontmatter found at top of script.")
    fm = {}
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        # strip inline comments like "date: 2026-07-06" or "hosts: [PRIYA, JIM]  # digest: ..."
        val = val.split("#", 1)[0].strip()
        fm[key.strip()] = val
    return fm


def extract_description(md: str, fallback_title: str) -> str:
    m = re.search(r"\*\*Running order\*\*\s*\n((?:\d+\..*\n?)+)", md)
    if m:
        items = [re.sub(r"^\d+\.\s*", "", ln).strip() for ln in m.group(1).splitlines() if ln.strip()]
        items = [i for i in items if i and not i.lower().startswith("quick-fire") and not i.lower().startswith("sign-off")]
        if items:
            return " • ".join(items[:6])

    # Deep-dives etc. use free-text Show notes instead of a numbered running order —
    # fall back to that paragraph (up to the next heading or the Sources line).
    m = re.search(r"##\s+Show notes\s*\n(?:<!--.*?-->\s*\n)?(.+?)(?:\n\n|\nSources:|\n##)", md, re.DOTALL)
    if m:
        text = " ".join(line.strip() for line in m.group(1).splitlines() if line.strip())
        if text:
            return text

    return fallback_title


def get_duration_seconds(mp3_path: Path) -> int:
    import imageio_ffmpeg
    ffmpeg = imageio_ffmpeg.get_ffmpeg_exe()
    result = subprocess.run(
        [ffmpeg, "-i", str(mp3_path)],
        capture_output=True, text=True,
    )
    m = re.search(r"Duration:\s*(\d+):(\d+):(\d+)\.(\d+)", result.stderr)
    if not m:
        return 0
    h, mnt, s, _ = m.groups()
    return int(h) * 3600 + int(mnt) * 60 + int(s)


def load_manifest() -> list[dict]:
    if not MANIFEST.exists():
        return []
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def save_manifest(episodes: list[dict]) -> None:
    MANIFEST.write_text(json.dumps(episodes, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def run(cmd: list[str], cwd: Path) -> None:
    result = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stdout + result.stderr)
        raise SystemExit(f"ERROR: command failed: {' '.join(cmd)}")


def main():
    if len(sys.argv) != 2:
        raise SystemExit("Usage: publish_episode.py <path\\to\\episode.md>")

    script_path = Path(sys.argv[1]).resolve()
    if not script_path.exists():
        raise SystemExit(f"ERROR: script not found: {script_path}")
    mp3_path = script_path.with_suffix(".mp3")
    if not mp3_path.exists():
        raise SystemExit(f"ERROR: no matching .mp3 found next to {script_path} — run tts/generate.py first.")

    md = script_path.read_text(encoding="utf-8")
    fm = parse_frontmatter(md)
    show = fm.get("show", "main")
    title = fm.get("title", script_path.stem)
    date = fm.get("date", "")
    if not date:
        raise SystemExit("ERROR: frontmatter has no 'date' field.")

    guid = f"{show}-{script_path.stem}"
    dest_filename = f"{show}-{script_path.stem}.mp3"
    dest_path = EPISODES_DIR / dest_filename

    EPISODES_DIR.mkdir(exist_ok=True)
    dest_path.write_bytes(mp3_path.read_bytes())

    duration = get_duration_seconds(dest_path)
    size_bytes = dest_path.stat().st_size
    description = extract_description(md, title)

    episodes = load_manifest()
    episodes = [e for e in episodes if e["guid"] != guid]  # replace if re-published
    episodes.append({
        "guid": guid,
        "show": show,
        "title": title,
        "pub_date": f"{date}T06:30:00+01:00" if show == "main" else (
            f"{date}T07:15:00+01:00" if show == "digest" else f"{date}T12:00:00+01:00"
        ),
        "description": description,
        "filename": dest_filename,
        "duration_seconds": duration,
        "file_size_bytes": size_bytes,
    })
    save_manifest(episodes)

    run([sys.executable, str(HERE / "generate_feed.py")], cwd=HERE)

    run(["git", "add", "-A"], cwd=HERE)
    commit_result = subprocess.run(
        ["git", "commit", "-m", f"Publish: [{show}] {title}"],
        cwd=str(HERE), capture_output=True, text=True,
    )
    if commit_result.returncode != 0 and "nothing to commit" not in commit_result.stdout:
        sys.stderr.write(commit_result.stdout + commit_result.stderr)
        raise SystemExit("ERROR: git commit failed.")
    run(["git", "push"], cwd=HERE)

    print(f"Published '{title}' ({show}, {duration}s, {size_bytes} bytes) -> {dest_filename}")


if __name__ == "__main__":
    main()
